name: 📈 Upload to Supabase Daily

on:
  schedule:
    - cron: '0 7 * * 1-5'  # ✅ 台灣時間 15:00（UTC+8 → UTC 07:00）
  workflow_dispatch:       # ✅ 可手動觸發
jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: 🧾 Checkout code
      uses: actions/checkout@v3

    - name: 📦 Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 📥 Install dependencies
      run: |
        pip install twstock pandas python-dotenv supabase beautifulsoup4 requests

    - name: 🛠 Run upload script
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
      run: python superbase_upload.py
